<?php
namespace AnhNhan\Symbols\Console;

use AnhNhan\Symbols\SymbolGenerator;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputDefinition;
use YamwLibs\Functions\FileFunc;
use YamwLibs\Infrastructure\Printers\ArrayPrinter;

/**
 * @author Anh Nhan Nguyen <anhnhan@outlook.com>
 */
final class SymbolGenerationCommand extends \Symfony\Component\Console\Command\Command
{
    protected function configure()
    {
        $this
            ->setName("symbols:generate")
            ->setDefinition($this->createDefinition())
            ->setDescription("Generate symbol definition list");
    }

    private function createDefinition()
    {
        return new InputDefinition(array(
            new InputArgument("path", InputArgument::OPTIONAL,
                "The path to discover files from and where to write the symbol " .
                "map to. Standard is to assume that we are in the Composer vendor/bin " .
                "directory, and we'll guess the project root (that is, we're going to " .
                "discover all things including the vendor dir)"
            ),
            new InputOption("no-git", null, InputOption::VALUE_NONE, "Don't use Git to discover files"),
        ));
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $useGit = !$input->getOption("no-git");
        $basePath = $input->getOption("path") ?: dirname(dirname(dirname(dirname(dirname(__FILE__)))));
        $basePath .= "/";

        if ($useGit) {
            $output->writeln("Using Git to discover files");
            $files = $this->discoverFilesGit($basePath);
            $files = preg_grep("/\\.php$/", $files);
        } else {
            $output->writeln("Not using Git to discover files");
            $files = $this->discoverFiles($basePath);
        }

        $fileCount = count($files);
        $output->writeln("Analyzing $fileCount files...");

        // Now begins the cool part :D
        $symbolGenerator = new SymbolGenerator($basePath);
        $skipped = array();

        $filesToBeParsed = array();
        foreach ($files as $file) {
            if (preg_match("/Test\\.php$/i", $file)) {
                echo "S";
                $skipped[] = $file;
                continue;
            }
            $filesToBeParsed[] = $file;
        }
        $symbolGenerator->addFiles($filesToBeParsed);

        $symbolGenerator->onFileTraverse(function ($fileName) use ($output) {
            $output->write(".");
        });

        $symbolGenerator->start();

        $symbolTree = $symbolGenerator->getTree();

        $output->writeln("");

        $output->writeln("Writing to disk...");

        $arrayPrinter = new ArrayPrinter();

        ob_start();
        echo <<<EOT
<?php
// -----------------------------------------------------------------------------
/**
 *  This file was generated by the SymbolGenerator(tm)
 *  Would be cool if you wouldn't edit it, as that would sure break things
 *
 *  To re-generate this file, run `php -f scripts/generate_symbol_list.php`
 *
 *  Thank you
 *  @love Anh Nhan <anhnhan@outlook.com>
 *
 *  @generated
 */
// -----------------------------------------------------------------------------
EOT;

        $symbolMapString = ob_get_clean();
        $symbolMapString .= $arrayPrinter->printForFile($symbolTree->toSymbolMap());

        file_put_contents(
            $basePath . "__symbol_map__.php",
            $symbolMapString
        );

        $output->writeln("Successfully wrote to disk!");
    }

    private function generateSymbolTree($nodes)
    {
        $symbolTreeGenerator = new SymbolTreeGenerator($nodes);
        $symbolTreeGenerator->generate();
        return $symbolTreeGenerator->getGeneratedTree();
    }

    private function discoverFilesGit($path)
    {
        $curDir = getcwd();

        $retVal = -1;
        chdir($path);
        exec('git ls-files', $rawFiles, $retVal);
        if ($retVal !== 0) {
            throw new \Exception("Git failed!");
        }
        $files = FileFunc::sanitizeStringsFromPrefix(
            $rawFiles,
            'src/'
        );

        // Change back to original directory
        chdir($curDir);

        return $files;
    }

    private function discoverFiles($path)
    {
        $rawFiles = FileFunc::recursiveScanForDirectories($path, '\.php');
        $files = FileFunc::sanitizeStringsFromPrefix($rawFiles, $path);
        return $files;
    }
}
